<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'FluidTYPO3\\Fluidcontent\\' => array($typo3InstallDir . 'typo3conf/ext/fluidcontent/Classes'),
    'FluidTYPO3\\Fluidpages\\' => array($typo3InstallDir . 'typo3conf/ext/fluidpages/Classes'),
    'FluidTYPO3\\Flux\\' => array($typo3InstallDir . 'typo3conf/ext/flux/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
);
